spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:~/testdb;NON_KEYWORDS=USER
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: never
server:
  port: 8080
  servlet:
    context-path: /api