<<<<<<< HEAD
"use client"
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { useEffect } from 'react'
import styled from 'styled-components';

const inter = Inter({ subsets: ['latin'] })

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
=======
"use client";
import { useEffect, useState } from "react";
import "../styles/globals.css";
import type { Metadata } from "next";
import Head from "next/head";
import { Inter } from "next/font/google";
import styled from "styled-components";
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
>>>>>>> 2336477077371476503281137f002afe49cc1af9

const Centering = styled.div`
  display: flex;
  justify-content: center;
`;
const FixedWidth = styled.div`
  width: 500px;
<<<<<<< HEAD
  @media (max-width: 500px) { /* 화면 너비가 500px 이하가 되면 요소 너비를 100%로 고정*/
=======
  min-height: 700px;
  @media (max-width: 500px) {
    /* 화면 너비가 500px 이하가 되면 요소 너비를 100%로 고정*/
>>>>>>> 2336477077371476503281137f002afe49cc1af9
    width: 100%;
  }
`;

// 모바일 세로 사이즈에 맞게 주소창 제외하고 세로 화면 계산하여 맞추기
function setScreenSize() {
  let vh = window.innerHeight;
<<<<<<< HEAD
  if (document.querySelector("#layout")) {
    document.querySelector("#layout").style.setProperty("height", `${vh}px`);
    // console.log(document.querySelector("#layout").style);
=======
  const layout = document.querySelector("#layout") as HTMLElement;
  if (layout) {
    layout.style.setProperty("height", `${vh}px`);
>>>>>>> 2336477077371476503281137f002afe49cc1af9
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
<<<<<<< HEAD
  
  useEffect(() => {
    setScreenSize();
  }, []);
  return (
    <html lang="en">
      <body className={inter.className}>
      <Centering>
      <FixedWidth id="layout">
        {children}
      </FixedWidth>
    </Centering>
    </body>
=======
  // 모바일 세로 사이즈에 맞게 주소창 제외하고 세로 화면 계산하여 맞추기
  function setScreenSize() {
    let vh = window.innerHeight;
    const layout = document.querySelector("#layout") as HTMLElement;
    if (layout.style) {
      layout.style.setProperty("height", `${vh}px`);
    }
  }

  useEffect(() => {
    setScreenSize();
  }, []);

  return (
    <html lang="ko-KR" suppressHydrationWarning={true}>
      <head></head>
      <body className={inter.className} suppressHydrationWarning={true}>
        <Centering>
          <FixedWidth id="layout" className="border-2 border-amber-300">
            {children}
          </FixedWidth>
        </Centering>
      </body>
>>>>>>> 2336477077371476503281137f002afe49cc1af9
    </html>
  )
}
