"use client"
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { useEffect } from 'react'
import styled from 'styled-components';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const Centering = styled.div`
  display: flex;
  justify-content: center;
`;
const FixedWidth = styled.div`
  width: 500px;
  @media (max-width: 500px) { /* 화면 너비가 500px 이하가 되면 요소 너비를 100%로 고정*/
    width: 100%;
  }
`;

// 모바일 세로 사이즈에 맞게 주소창 제외하고 세로 화면 계산하여 맞추기
function setScreenSize() {
  let vh = window.innerHeight;
  if (document.querySelector("#layout")) {
    document.querySelector("#layout").style.setProperty("height", `${vh}px`);
    console.log(document.querySelector("#layout").style);
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  useEffect(() => {
    setScreenSize();
  }, []);
  return (
    <html lang="en">
      <body className={inter.className}>
      <Centering>
      <FixedWidth id="layout">
        {children}
      </FixedWidth>
    </Centering>
    </body>
    </html>
  )
}
