# https://www.docker.elastic.co/
FROM opensearchproject/logstash-oss-with-opensearch-output-plugin:latest

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
